workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - cd ios && pod install --repo-update && cd ..
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
