name: thankinh_pex
description: Ứng dụng theo dõi thay huyết tương (PEX) nội bộ.

publish_to: "none" # Không publish lên pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  file_picker: ^6.2.0
  path_provider: ^2.1.2
  wifi_iot: ^0.3.18
  multicast_dns: ^0.3.1
  flutter_local_notifications: ^17.1.0
  permission_handler: ^12.0.0+1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
