name: thankinh_pex
description: Ứng dụng theo dõi thay huyết tương (PEX) nội bộ.

publish_to: "none" # Không publish lên pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  file_picker: ^8.3.2
  path_provider: ^2.1.5
  wifi_iot: ^0.3.19+2
  multicast_dns: ^0.3.3
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  signature: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
