platform :ios, '13.0'  
use_frameworks! :linkage => :static 

flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_application_path = File.expand_path('..', __FILE__)
load File.join(flutter_application_path, 'Flutter', 'podhelper.rb'))


end
