platform :ios, '13.0'  
use_frameworks! :linkage => :static 

flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_install_all_ios_pods(flutter_application_path)
end
